### ISSUE TITLE
 Meshes Model "oak_tree" meshes does not exist

### ISSUE THREAD

**Issue by LuisYordano** [PanosMallioris/Autonomous-Marine-Exploration-Water-Simulation-ROS-GAZEBO#1]
Hi Panos,

Could you upload the meshes "oak_tree" model at your repository to execute the second world : `roslaunch auv marine.launch`

![selection_009](https://user-images.githubusercontent.com/13818395/53350185-9b45f000-38ec-11e9-8087-d534d2317c10.png)

Thanks in advance for your answer.

**Comment by PanosMallioris** [comment]
Hello Luis thanks for the response,

Do you have any problem executing the world cause of this mesh? 

I guess the gazebo has by default all this meshes, i dont have any of them in my workspace.

Do you have the same issue with the buildings also ? cause they also have meshes.

Is the gazebo version that you are using that doesn't contain this oak tree? 

If you want to open the world try to delete every part of code in the marine.world file that has the oak tree and try again.

Another thing that you can try is to open an empty gazebo world $ gazebo and try to find and implement the oak tree        / insert -> http://models.gazebosim... -> oak tree

**Comment by LuisYordano** [comment]
Hi Panos,
Thanks for  you answer,
In you video youtube show "Target recognition is being also implemented"

![selection_010](https://user-images.githubusercontent.com/13818395/53418192-339fab80-39a5-11e9-80ff-e76c446c2c9c.png)

----

Could write what is the command to run this demo, because python auv_safe.py and python auv_marine.py are almost the same code.

Thanks in advance for your answer.

**Comment by PanosMallioris** [comment]
Hello Luis 

I have updated the Readme file to answer your question.
Note that i have also added the human package for this so you will have to add it on your src workspace also, or git clone the repository again.

Thanks for the response!

**Comment by LuisYordano** [comment]
Thanks Panos, for sharing your code and the instructions to execute it correctly.
